#Create a deployment with image nginx:1.7.8, called nginx,
#having 2 replicas,
#defining port 80 as the port that this container exposes (don't create a service for this deployment)

apiVersion: apps/v1
kind: Deployment
metadata:
  #Deployment name
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      #Refer to pod label
      name: nginx
  template:
    # From pod-definition
    metadata:
      name: nginx
      #For reference
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx-pod
          image: nginx:1.7.8
          ports:
            - containerPort: 80

