#Create a pod with the given specifications.
#By default it displays a 'blue' background.
#Set the given command line arguments to change it to 'green'
apiVersion: v1
kind: Pod
metadata:
  name: webapp-green
spec:
  containers:
    - name: webapp-green
      image: kodekloud/webapp-color
      args: ["--color","green"]