apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-05-23T06:19:10Z"
  labels:
    name: simple-webapp
  name: simple-webapp-2
  namespace: default
  resourceVersion: "1291"
  selfLink: /api/v1/namespaces/default/pods/simple-webapp-2
  uid: 980f77c0-84cd-4ec6-acf2-1427723cd377
spec:
  containers:
    - env:
        - name: APP_START_DELAY
          value: "80"
      image: kodekloud/webapp-delayed-start
      imagePullPolicy: Always
      name: simple-webapp
      ports:
        - containerPort: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 90
        periodSeconds: 3
      resources: {}

      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:

        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-k2srh
          readOnly: true

  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node01
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: default-token-k2srh
      secret:
        defaultMode: 420
        secretName: default-token-k2srh
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-05-23T06:19:10Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2020-05-23T06:19:13Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2020-05-23T06:19:13Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2020-05-23T06:19:10Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: docker://9ab77cba8fb33dbba5585ee55e97138f7bb75f0659d2bf7c99973828cf16994a
      image: kodekloud/webapp-delayed-start:latest
      imageID: docker-pullable://kodekloud/webapp-delayed-start@sha256:666b95c2ef8e00a74fa0ea96def8d9d69104ec5d9b9b0f49d8a76bd4c94ad343
      lastState: {}
      name: simple-webapp
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2020-05-23T06:19:12Z"
  hostIP: 172.17.0.22
  phase: Running
  podIP: 10.44.0.3
  podIPs:
    - ip: 10.44.0.3
  qosClass: BestEffort
  startTime: "2020-05-23T06:19:10Z"