apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-1
spec:
  containers:
    - name: simple-webapp-1
      image: kodekloud/webapp-delayed-start
      livenessProbe:
        httpGet:
          port: 8080
          path: /live
        #Frequency
        periodSeconds: 10
        #Startup seconds
        initialDelaySeconds: 80
        #re try Failure
        failureThreshold: 1