apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress-space
spec:

  ports:


    - port: 80
      nodePort: 30080
      targetPort: 80

  type: NodePort
  selector:
    name: nginx-ingress