apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu
      command: ["sleep","10"]
      securityContext:
        runAsUser: 1010
        capabilities:
          add: ["root", "SYS_TIME"]
        privileged: false