#Create a pod with image nginx called nginx and expose traffic on port 80

controlplane $ kubectl run nginx --image=nginx --dry-run=client -o yaml -n default --port=80
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
  controlplane $ kubectl run nginx --image=nginx -n default --port=80
  pod/nginx created