#Create a pod that will be deployed to a Node that has the label 'accelerator=nvidia-tesla-p100'

# step1 :-
# Add label on node
# $kubectl label node nodename accelerator=nvidia-tesla-p100

# Step2 :-
#Create pod with node affinity
#$kubectl run nginx --image=nginx --dry-run=client -o yaml > po.yml
#vi po.yml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: accelerator
            operator: In
            values:
            - nvidia-tesla-p100